<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Prophet.Api</RootNamespace>
    <UserSecretsId>prophet-api-local-dev</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Prophet.Application\Prophet.Application.csproj" />
    <ProjectReference Include="..\Prophet.Adapters.LLM\Prophet.Adapters.LLM.csproj" />
    <ProjectReference Include="..\Prophet.Adapters.InMemory\Prophet.Adapters.InMemory.csproj" />
    <ProjectReference Include="..\Prophet.CrossCutting\Prophet.CrossCutting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
</Project>
