<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <RootNamespace>Prophet.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Prophet.Application\Prophet.Application.csproj" />
    <ProjectReference Include="..\Prophet.Adapters.LLM\Prophet.Adapters.LLM.csproj" />
    <ProjectReference Include="..\Prophet.Adapters.LocalStorage\Prophet.Adapters.LocalStorage.csproj" />
    <ProjectReference Include="..\Prophet.Adapters.Postgres\Prophet.Adapters.Postgres.csproj" />
    <ProjectReference Include="..\Prophet.CrossCutting\Prophet.CrossCutting.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.OpenApi" />
    <PackageReference Include="Serilog.AspNetCore" />
  </ItemGroup>
</Project>
