<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Prophet.Application\Prophet.Application.csproj" />
    <ProjectReference Include="..\Prophet.Domain\Prophet.Domain.csproj" />
    <ProjectReference Include="..\Prophet.CrossCutting\Prophet.CrossCutting.csproj" />
    <ProjectReference Include="..\Prophet.Adapters.LLM\Prophet.Adapters.LLM.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Moq" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
